import type { Metadata } from "next";
import React from "react";
import '../sass/main.scss';
import Header from "@/app/_components/Layout/Header";
import Footer from "@/app/_components/Layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  );
}
